In [5]:
pip install numpy pandas matplotlib seaborn

Requirement already satisfied: numpy in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.5.2)
Requirement already satisfied: pandas in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: matplotlib in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.11.1)
Requirement already satisfied: seaborn in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv('C:/Users/LENOVO/OneDrive/Desktop/combined_data_1.txt',header=None,names=['cust_id','Ratings'],usecols=[0,1])

In [8]:
df

          cust_id  Ratings
0              1:      NaN
1         1488844      3.0
2          822109      5.0
3          885013      4.0
4           30878      4.0
...           ...      ...
24058258  2591364      2.0
24058259  1791000      2.0
24058260   512536      5.0
24058261   988963      3.0
24058262  1704416      3.0

[24058263 rows x 2 columns]

In [9]:
# movie count 
Movie_count= df.isna().sum()['Ratings']
Movie_count

np.int64(4499)

In [10]:
# total unique customer
total_uniq = df['cust_id'].nunique()
total_uniq

475257

In [11]:
cust_count = total_uniq-Movie_count
cust_count

np.int64(470758)

In [12]:
Ratings_count= df['Ratings'].count() - Movie_count
Ratings_count

np.int64(24049265)

In [13]:
stars_count = df['Ratings'].value_counts()
stars_count

Ratings
4.0    8085741
3.0    6904181
5.0    5506583
2.0    2439073
1.0    1118186
Name: count, dtype: int64

In [14]:
# creating movie id column
movie_id = None
movie_list = []
for customer in df['cust_id']:
    if ":" in customer:
        movie_id = int(customer.replace(':',""))
    movie_list.append(movie_id)

In [15]:
movie_list

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [16]:
df['Movie_id']= movie_list
df

          cust_id  Ratings  Movie_id
0              1:      NaN         1
1         1488844      3.0         1
2          822109      5.0         1
3          885013      4.0         1
4           30878      4.0         1
...           ...      ...       ...
24058258  2591364      2.0      4499
24058259  1791000      2.0      4499
24058260   512536      5.0      4499
24058261   988963      3.0      4499
24058262  1704416      3.0      4499

[24058263 rows x 3 columns]

In [17]:
df.dropna(inplace=True)

In [18]:
df

          cust_id  Ratings  Movie_id
1         1488844      3.0         1
2          822109      5.0         1
3          885013      4.0         1
4           30878      4.0         1
5          823519      3.0         1
...           ...      ...       ...
24058258  2591364      2.0      4499
24058259  1791000      2.0      4499
24058260   512536      5.0      4499
24058261   988963      3.0      4499
24058262  1704416      3.0      4499

[24053764 rows x 3 columns]

In [19]:
df.info()

<class 'pandas.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   cust_id   str
 1   Ratings   float64
 2   Movie_id  int64
dtypes: float64(1), int64(1), str(1)
memory usage: 734.1 MB

In [20]:
df['cust_id'] = df['cust_id'].astype('int')
df.info()

<class 'pandas.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   cust_id   int64
 1   Ratings   float64
 2   Movie_id  int64
dtypes: float64(1), int64(2)
memory usage: 734.1 MB

In [21]:
movie_rat_count=df['Movie_id'].value_counts()
movie_rat_count

Movie_id
1905    193941
2152    162597
3860    160454
4432    156183
571     154832
         ...
4294        44
915         43
3656        42
4338        39
4362        36
Name: count, Length: 4499, dtype: int64

In [22]:
bench_marks1=round(movie_rat_count.quantile(0.6),0)
bench_marks1

np.float64(908.0)

In [23]:
# what movies id we need to remove .
drop_movie_index=movie_rat_count[movie_rat_count<bench_marks1].index
drop_movie_index

Index([1598, 1647, 1733, 4099, 1616,  263, 1446,  160, 4259,  322,
       ...
       1858, 4035, 3693, 2805,  820, 4294,  915, 3656, 4338, 4362],
      dtype='int64', name='Movie_id', length=2699)

In [24]:
cust_rat_count=df['cust_id'].value_counts()
cust_rat_count

cust_id
305344     4467
387418     4422
2439493    4195
1664010    4019
2118461    3769
           ...
1103924       1
715803        1
1017887       1
72311         1
594210        1
Name: count, Length: 470758, dtype: int64

In [25]:
bench_marks2=round(cust_rat_count.quantile(0.6),0)
bench_marks2

np.float64(36.0)

In [26]:
drop_cust_index=cust_rat_count[cust_rat_count<bench_marks2].index
drop_cust_index

Index([2088415, 1340535, 1288603, 2072554, 1479793, 1927897, 1144273, 1098735,
       1528767,  556249,
       ...
       1504246,  863933, 1314464,  412588,  207571, 1103924,  715803, 1017887,
         72311,  594210],
      dtype='int64', name='cust_id', length=282042)

In [27]:
drop_movie_index,drop_cust_index

(Index([1598, 1647, 1733, 4099, 1616,  263, 1446,  160, 4259,  322,
        ...
        1858, 4035, 3693, 2805,  820, 4294,  915, 3656, 4338, 4362],
       dtype='int64', name='Movie_id', length=2699),
 Index([2088415, 1340535, 1288603, 2072554, 1479793, 1927897, 1144273, 1098735,
        1528767,  556249,
        ...
        1504246,  863933, 1314464,  412588,  207571, 1103924,  715803, 1017887,
          72311,  594210],
       dtype='int64', name='cust_id', length=282042))

In [28]:
df=df[~df['Movie_id'].isin(drop_movie_index)]
df=df[~df['cust_id'].isin(drop_cust_index)]

In [29]:
df

          cust_id  Ratings  Movie_id
696        712664      5.0         3
697       1331154      4.0         3
698       2632461      3.0         3
699         44937      5.0         3
700        656399      4.0         3
...           ...      ...       ...
24056842  1055714      5.0      4496
24056843  2643029      4.0      4496
24056844   267802      4.0      4496
24056845  1559566      3.0      4496
24056846   293198      3.0      4496

[19695836 rows x 3 columns]

In [30]:
# Data filter is done

In [31]:
movie_title=pd.read_csv('C:/Users/LENOVO/Downloads/movie_titles.csv',encoding='ISO-8859-1',header=None,names=['Movie_ID','Year','Name'],usecols=[0,1,2])

In [32]:
movie_title

       Movie_ID    Year                                               Name
0             1  2003.0                                    Dinosaur Planet
1             2  2004.0                         Isle of Man TT 2004 Review
2             3  1997.0                                          Character
3             4  1994.0                       Paula Abdul's Get Up & Dance
4             5  2004.0                           The Rise and Fall of ECW
...         ...     ...                                                ...
17765     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766     17767  2004.0                  Fidel Castro: American Experience
17767     17768  2000.0                                              Epoch
17768     17769  2003.0                                        The Company
17769     17770  2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [33]:
!pip install scikit-surprise
!pip install surprise

Requirement already satisfied: scikit-surprise in C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.1.5)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-surprise) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-surprise) (1.18.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: surprise in C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.1)
Requirement already satisfied: scikit-surprise in C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from surprise) (1.1.5)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-surprise->surprise) (1.5.3)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-surprise->surprise) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-surprise->surprise) (1.18.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
from surprise import Reader,Dataset,SVD
from surprise.model_selection import cross_validate

In [35]:
from surprise.model_selection import cross_validate

In [42]:
reader = Reader()
df.columns

Index(['cust_id', 'Ratings', 'Movie_id'], dtype='str')

In [43]:
data=Dataset.load_from_df(df[['Movie_id','cust_id','Ratings']][:100000],reader)
#We are converting a pandas DF into surprise's internal format so SVd can learn from it.

In [44]:
data

In [45]:
model=SVD()

In [46]:
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([1.01689812, 1.01781165, 1.0151795 ]),
 'fit_time': (2.3351070880889893, 2.423332452774048, 2.2932188510894775),
 'test_time': (0.3364722728729248, 0.31118178367614746, 0.29036641120910645)}

In [48]:
# 1331154	---cust_id
user_1331154=df[df['cust_id']==1331154]
user_1331154

          cust_id  Ratings  Movie_id
697       1331154      4.0         3
5178      1331154      4.0         8
31460     1331154      3.0        18
92840     1331154      4.0        30
224761    1331154      3.0        44
...           ...      ...       ...
23439584  1331154      4.0      4389
23546489  1331154      2.0      4402
23649431  1331154      4.0      4432
23844441  1331154      3.0      4472
23985561  1331154      4.0      4488

[253 rows x 3 columns]

In [49]:
dummy_title=movie_title.copy()
dummy_title

       Movie_ID    Year                                               Name
0             1  2003.0                                    Dinosaur Planet
1             2  2004.0                         Isle of Man TT 2004 Review
2             3  1997.0                                          Character
3             4  1994.0                       Paula Abdul's Get Up & Dance
4             5  2004.0                           The Rise and Fall of ECW
...         ...     ...                                                ...
17765     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766     17767  2004.0                  Fidel Castro: American Experience
17767     17768  2000.0                                              Epoch
17768     17769  2003.0                                        The Company
17769     17770  2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [50]:
dummy_title=dummy_title[~dummy_title['Movie_ID'].isin(drop_movie_index)]

In [51]:
dummy_title

       Movie_ID    Year                                               Name
2             3  1997.0                                          Character
4             5  2004.0                           The Rise and Fall of ECW
5             6  1997.0                                               Sick
7             8  2004.0                         What the #$*! Do We Know!?
15           16  1996.0                                          Screamers
...         ...     ...                                                ...
17765     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766     17767  2004.0                  Fidel Castro: American Experience
17767     17768  2000.0                                              Epoch
17768     17769  2003.0                                        The Company
17769     17770  2003.0                                       Alien Hunter

[15071 rows x 3 columns]

In [52]:
est_rating=[]
for movie in dummy_title['Movie_ID']:
  rating=model.predict(1331154,movie).est
  est_rating.append(rating)



dummy_title['Rating']=est_rating

In [53]:
dummy_title

,Movie_ID,Year,Name,Rating
2,3,1997.0,Character,3.577062
4,5,2004.0,The Rise and Fall of ECW,3.577062
5,6,1997.0,Sick,3.577062
7,8,2004.0,What the #$*! Do We Know!?,3.577062
15,16,1996.0,Screamers,3.577062
...,...,...,...,...
17765,17766,2002.0,Where the Wild Things Are and Other Maurice Se...,3.577062
17766,17767,2004.0,Fidel Castro: American Experience,3.577062
17767,17768,2000.0,Epoch,3.577062
17768,17769,2003.0,The Company,3.577062
17769,17770,2003.0,Alien Hunter,3.577062

In [55]:
dummy_title=dummy_title.sort_values('Rating',ascending=False)
dummy_title.head(5)

,Movie_ID,Year,Name,Rating
13874,13875,1982.0,Gilbert and Sullivan: The Mikado,3.853649
15673,15674,1999.0,Arlington Road,3.821664
10942,10943,2001.0,Ben Folds Five: Complete Sessions at West 54th,3.786382
13761,13762,1963.0,55 Days at Peking,3.782834
12536,12537,2003.0,Undermind,3.766651